/**
 * Presets de layout por estilo, fiéis aos templates de referência
 * (components/templates/tp_old). Cada botão "Estilo" seleciona um destes; o
 * editor visual ("Editar layout") abre seedado com o preset escolhido.
 * Todos derivam de DEFAULTS sobrescrevendo cores/tipografia/layout.
 */

import { DEFAULTS, type EmailLayoutConfig } from "@/lib/email/email-layout-config";
import type { EmailTemplateKey } from "@/lib/email-templates";

export const EMAIL_LAYOUT_PRESETS: Record<EmailTemplateKey, EmailLayoutConfig> = {
  // ── Profissional (gala — base) ──
  profissional: { ...DEFAULTS },

  // ── Elegante (preto + dourado, título itálico) ──
  elegante: {
    ...DEFAULTS,
    eyebrow: "✦ Convite Exclusivo ✦",
    title: "Noite de Gala",
    subtitle: "Atlas Awards 2026",
    headerDecor: "",
    greeting: "Você está convidado",
    greetingSize: 11,
    greetingUppercase: true,
    greetingSpacing: 2,
    greetingColor: "#0d0d0d",
    headerGradient: false,
    headerColor1: "#0d0d0d",
    headerBorderWidth: 0,
    accentColor: "#c9a84c",
    titleColor: "#f5f0e8",
    titleWeight: 400,
    titleItalic: true,
    subtitleColor: "#c9a84c",
    eyebrowSize: 9,
    eyebrowSpacing: 5,
    pageBg: "#f4f4f4",
    emailBg: "#faf8f5",
    cardBg: "#f0ece4",
    cardBorderSide: "top",
    cardBorderWidth: 2,
    cardBorderColor: "#c9a84c",
    cardRadius: 8,
    cardDividerColor: "#d8cfbf",
    strongTextColor: "#0d0d0d",
    normalTextColor: "#5a5040",
    footerGradient: false,
    footerBg: "#0d0d0d",
    footerTextColor: "#c9a84c",
    footerNoticeColor: "#444444",
  },

  // ── Minimalista (branco, traços, sem ícone de local) ──
  minimalista: {
    ...DEFAULTS,
    eyebrow: "Convite — 2026",
    title: "Noite de Gala\nAtlas Awards",
    subtitle: "",
    headerDecor: "",
    greeting: "Você está convidado",
    greetingSize: 11,
    greetingUppercase: true,
    greetingSpacing: 1,
    greetingColor: "#111111",
    headerGradient: false,
    headerColor1: "#ffffff",
    headerBorderWidth: 2,
    headerBorderColor: "#111111",
    headerAlign: "left",
    accentColor: "#999999",
    titleColor: "#111111",
    titleWeight: 300,
    titleItalic: false,
    titleSize: 32,
    eyebrowSize: 9,
    eyebrowSpacing: 4,
    pageBg: "#f4f4f4",
    emailBg: "#ffffff",
    cardBg: "#ffffff",
    cardBorderSide: "all",
    cardBorderWidth: 1,
    cardBorderColor: "#e8e8e8",
    cardRadius: 8,
    cardDividerColor: "#eeeeee",
    locationIcon: "—",
    strongTextColor: "#111111",
    normalTextColor: "#666666",
    footerGradient: false,
    footerBg: "#111111",
    footerTextColor: "#ffffff",
    footerNoticeColor: "#555555",
  },

  // ── Acolhedor (laranja quente, emoji) ──
  acolhedor: {
    ...DEFAULTS,
    eyebrow: "— com carinho —",
    title: "Noite de Gala\nAtlas Awards 2026",
    subtitle: "",
    headerDecor: "🌟",
    greeting: "Olá! Você está convidado 😊",
    greetingSize: 16,
    greetingUppercase: false,
    greetingSpacing: 0,
    greetingColor: "#7a3010",
    headerGradient: true,
    headerColor1: "#c85a2a",
    headerColor2: "#e07840",
    headerColor3: "#f0965a",
    gradientAngle: 135,
    accentColor: "#c85a2a",
    titleColor: "#ffffff",
    titleWeight: 700,
    titleItalic: false,
    eyebrowSize: 10,
    eyebrowSpacing: 2,
    pageBg: "#f4f4f4",
    emailBg: "#fffaf6",
    cardBg: "#fff2e8",
    cardBorderSide: "left",
    cardBorderWidth: 4,
    cardBorderColor: "#e07840",
    cardRadius: 10,
    cardDividerColor: "#f0d0b8",
    strongTextColor: "#7a3010",
    normalTextColor: "#8a5a40",
    signature: "Equipe Atlaz 🧡",
    footerGradient: true,
    footerBg: "#c85a2a",
    footerColor2: "#d46838",
    footerTextColor: "#ffe0c8",
    footerNoticeColor: "#f0c0a0",
  },
};
